apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress11
  namespace: monitoring 
spec:
  ingressClassName: nginx
  rules:
  - host: mongo.keyletgh.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: mongolb 
            port:
              number: 80
